#!/usr/bin/env python3
"""Generate idempotent SQL to import Glide's payroll export into Kova's
`payroll` schema (see supabase/migrations/0036_payroll_schema.sql).

Usage:
    python3 scripts/payroll_import.py "Payroll and Program Tracker.xlsx" \
        --out supabase/migrations/0037_payroll_seed_data.sql

Safe to re-run against a later export of the same Glide app: pay_entries
rows reuse Glide's own EntryID as their primary key (ON CONFLICT (id) DO
UPDATE), so an unchanged row is a no-op and an edited row is refreshed.
custom_requests rows have no stable id in the source data, so they dedupe
on (staff_email, pay_period_start, description, amount_requested) instead
— see the unique index in 0036 for why that's an accepted, documented
tradeoff rather than a guaranteed key.

This script only READS the xlsx and WRITES a .sql file — it never touches
a live database. Terra runs the generated file in the Supabase SQL Editor
herself, same as every other migration in this codebase.
"""

import argparse
import sys
from datetime import date, datetime

import openpyxl

# Glide's OtherType values that don't match anything in OtherRates — real
# entries used these, but they were typos for an existing rate. Confirmed
# with Terra: remap rather than treat as a new rate or leave at $0.
OTHER_TYPE_FIXES = {
    "Cleaning + BS": "Cleaning",
    "BWA": "BWA Programming",
}

# One known orphaned PayPeriodID typo in CustomPayrollRequests.
PAY_PERIOD_ID_FIXES = {
    "pp_2022_12_25": "pp_2025_12_25",
}


def sql_str(value):
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_num(value):
    if value is None or value == "":
        return "NULL"
    return repr(float(value))


def sql_int(value):
    if value is None or value == "":
        return "NULL"
    return str(int(float(value)))


def sql_bool(value):
    if value is None:
        return "NULL"
    return "true" if value else "false"


def sql_date(value):
    if value is None:
        return "NULL"
    if isinstance(value, datetime):
        value = value.date()
    if isinstance(value, date):
        return "'" + value.isoformat() + "'"
    return sql_str(value)


def sql_ts(value):
    if value is None:
        return "NULL"
    if isinstance(value, date) and not isinstance(value, datetime):
        value = datetime(value.year, value.month, value.day)
    return "'" + value.isoformat() + "'"


def clean_numeric(value):
    """Glide sometimes writes '' instead of leaving a numeric cell blank."""
    if value is None or value == "":
        return None
    return value


def load_sheet(wb, name):
    ws = wb[name]
    rows = list(ws.iter_rows(values_only=True))
    header = rows[0]
    return header, [r for r in rows[1:] if any(v is not None and v != "" for v in r)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("xlsx_path", help="Path to the exported Payroll and Program Tracker.xlsx")
    parser.add_argument("--out", default="supabase/migrations/0037_payroll_seed_data.sql")
    args = parser.parse_args()

    wb = openpyxl.load_workbook(args.xlsx_path, data_only=True)

    warnings = []

    # ---- Users: email -> name, for snapshotting staff_name/staff_email ----
    users_header, users_rows = load_sheet(wb, "Users")
    u_idx = {h: i for i, h in enumerate(users_header)}
    email_to_name = {}
    for r in users_rows:
        email = r[u_idx["Email"]]
        name = r[u_idx["Name"]]
        if email and name:
            email_to_name[email] = name

    # ---- PayPeriods: PayPeriodID -> (start_date, end_date, label, status) ----
    pp_header, pp_rows = load_sheet(wb, "PayPeriods")
    pp_idx = {h: i for i, h in enumerate(pp_header)}
    periods_by_id = {}
    for r in pp_rows:
        pid = r[pp_idx["PayPeriodID"]]
        if not pid:
            continue
        periods_by_id[pid] = {
            "label": r[pp_idx["Label"]],
            "start": r[pp_idx["StartDate"]],
            "end": r[pp_idx["EndDate"]],
            "status": r[pp_idx["Status"]],
        }

    def resolve_period_id(pid):
        if pid in PAY_PERIOD_ID_FIXES:
            fixed = PAY_PERIOD_ID_FIXES[pid]
            warnings.append(f"PayPeriodID '{pid}' remapped to '{fixed}' (typo fix)")
            pid = fixed
        return pid

    # ---- OtherRates: valid OtherType set, for a defensive check ----
    or_header, or_rows = load_sheet(wb, "OtherRates")
    or_idx = {h: i for i, h in enumerate(or_header)}
    valid_other_types = {r[or_idx["OtherType"]] for r in or_rows if r[or_idx["OtherType"]]}

    def resolve_other_type(value):
        if not value:
            return None
        if value in OTHER_TYPE_FIXES:
            return OTHER_TYPE_FIXES[value]
        return value

    lines = []
    lines.append("-- Generated by scripts/payroll_import.py from")
    lines.append(f"-- {args.xlsx_path!r} — DO NOT hand-edit, regenerate instead.")
    lines.append("-- Safe to re-run: pay_entries upserts on id (Glide's own EntryID),")
    lines.append("-- custom_requests dedupes on (staff_email, pay_period_start, description,")
    lines.append("-- amount_requested). Run this in the Supabase SQL Editor after 0036, then")
    lines.append("-- NOTIFY pgrst, 'reload schema';")
    lines.append("")

    # ---- pay_periods: only Closed + Open (historical fact + the current
    # period) — Upcoming rows are deliberately skipped, the new system
    # creates those lazily when they're actually needed. ----
    lines.append("-- Pay periods (historical + current only; upcoming periods are")
    lines.append("-- intentionally not pre-seeded — see payroll.ensure_pay_period()).")
    period_rows_sql = []
    imported_period_starts = set()
    for pid, p in periods_by_id.items():
        if p["status"] not in ("Closed", "Open"):
            continue
        start = p["start"]
        if isinstance(start, datetime):
            start = start.date()
        end = p["end"]
        if isinstance(end, datetime):
            end = end.date()
        closed = p["status"] == "Closed"
        imported_period_starts.add(start)
        period_rows_sql.append(
            f"({sql_date(start)}, {sql_str(p['label'])}, {sql_str(pid)}, {sql_bool(closed)}, "
            f"{sql_ts(datetime.now()) if closed else 'NULL'}, NULL)"
        )
    if period_rows_sql:
        lines.append(
            "insert into payroll.pay_periods (start_date, label, legacy_period_id, closed, closed_at, closed_by) values"
        )
        lines.append(",\n".join(period_rows_sql) + "")
        lines.append(
            "on conflict (start_date) do update set label = excluded.label, "
            "legacy_period_id = excluded.legacy_period_id;"
        )
        lines.append(
            "-- Note: closed/closed_at/closed_by are deliberately NOT in the DO UPDATE clause —"
        )
        lines.append(
            "-- re-running this script must never overwrite a close decision made in the new app."
        )
    lines.append("")

    # ---- pay_entries ----
    pe_header, pe_rows = load_sheet(wb, "PayEntries")
    pe_idx = {h: i for i, h in enumerate(pe_header)}
    entries_sql = []
    legacy_id_to_amount = {}  # for cross-linking custom_requests below
    skipped_entries = 0
    seen_entry_ids = set()
    duplicate_entry_ids = 0

    for r in pe_rows:
        entry_id = r[pe_idx["EntryID"]]
        if not entry_id:
            continue
        if entry_id in seen_entry_ids:
            # A genuine Glide export artifact, not a data-modeling issue:
            # a handful of EntryIDs appear twice in the raw sheet as
            # otherwise byte-identical rows (same date/coach/content, only
            # Glide's internal hidden Row ID differs) — almost certainly
            # the same real event duplicated in the underlying Google
            # Sheet, not two legitimately distinct entries that happen to
            # share an id. EntryID is our primary key (ON CONFLICT (id) DO
            # UPDATE), so a second row with the same id inside the SAME
            # insert statement would 21000 ("cannot affect row a second
            # time") — keep only the first occurrence.
            duplicate_entry_ids += 1
            warnings.append(f"pay_entries: dropped duplicate row for EntryID {entry_id} (appears twice in the source export)")
            continue
        seen_entry_ids.add(entry_id)
        email = r[pe_idx["StaffEmail"]]
        pay_period_id = r[pe_idx["PayPeriodID"]]
        period = periods_by_id.get(pay_period_id)
        if email not in email_to_name or not period:
            skipped_entries += 1
            warnings.append(
                f"pay_entries: skipped EntryID {entry_id} (email={email!r}, period={pay_period_id!r} unresolved)"
            )
            continue
        start = period["start"]
        if isinstance(start, datetime):
            start = start.date()
        if start not in imported_period_starts:
            # Referenced an Upcoming period that was skipped above — pull it in too.
            imported_period_starts.add(start)

        other_type_raw = r[pe_idx["OtherType"]]
        other_type = resolve_other_type(other_type_raw)
        if other_type and other_type not in valid_other_types and other_type not in OTHER_TYPE_FIXES.values():
            warnings.append(f"pay_entries: EntryID {entry_id} has unmatched OtherType {other_type_raw!r}")

        spc_attendees_raw = r[pe_idx["SPC_Attendees"]]
        spc_attendees = spc_attendees_raw if isinstance(spc_attendees_raw, (int, float)) else None

        custom_amt = r[pe_idx["Custom_Amt"]]
        if custom_amt is not None:
            legacy_id_to_amount[entry_id] = (email, float(custom_amt))

        entries_sql.append(
            "(" + ", ".join([
                sql_str(entry_id),
                f"(select id from core.users where email = {sql_str(email)})",
                sql_str(email_to_name[email]),
                sql_str(email),
                sql_date(start),
                sql_date(r[pe_idx["EntryDate"]]),
                sql_num(clean_numeric(r[pe_idx["GroupSessions"]])),
                sql_num(clean_numeric(r[pe_idx["ProgramsWritten"]])),
                sql_num(clean_numeric(r[pe_idx["AdminHours"]])),
                sql_num(clean_numeric(r[pe_idx["WelcomeSessions"]])),
                sql_num(clean_numeric(r[pe_idx["StrategySessions"]])),
                sql_num(clean_numeric(r[pe_idx["OpsHours"]])),
                sql_bool(r[pe_idx["SPC_Session"]] if isinstance(r[pe_idx["SPC_Session"]], bool) else None),
                sql_int(spc_attendees),
                sql_str(other_type),
                sql_num(clean_numeric(r[pe_idx["OtherQty"]])) if clean_numeric(r[pe_idx["OtherQty"]]) is not None else "1",
                sql_num(clean_numeric(r[pe_idx["Custom_Amt"]])),
                sql_str(r[pe_idx["Custom Description"]]),
                sql_str(r[pe_idx["Notes"]]),
                sql_str(r[pe_idx["SPC_Notes"]]),
                sql_str(r[pe_idx["Program_Notes"]]),
                sql_str(r[pe_idx["Welcome_Notes"]]),
                sql_str(r[pe_idx["AdminNotes"]]),
                "'legacy_import'",
                sql_str(entry_id),
            ]) + ")"
        )

    pay_entries_insert_header = (
        "insert into payroll.pay_entries (id, user_id, staff_name, staff_email, pay_period_start, "
        "entry_date, group_sessions, programs_written, admin_hours, welcome_sessions, strategy_sessions, "
        "ops_hours, spc_session, spc_attendees, other_type, other_qty, custom_amt, custom_description, "
        "notes, spc_notes, program_notes, welcome_notes, admin_notes, source, legacy_entry_id) values"
    )
    pay_entries_on_conflict = (
        "on conflict (id) do update set "
        "group_sessions = excluded.group_sessions, programs_written = excluded.programs_written, "
        "admin_hours = excluded.admin_hours, welcome_sessions = excluded.welcome_sessions, "
        "strategy_sessions = excluded.strategy_sessions, ops_hours = excluded.ops_hours, "
        "spc_session = excluded.spc_session, spc_attendees = excluded.spc_attendees, "
        "other_type = excluded.other_type, other_qty = excluded.other_qty, custom_amt = excluded.custom_amt, "
        "custom_description = excluded.custom_description, notes = excluded.notes, "
        "spc_notes = excluded.spc_notes, program_notes = excluded.program_notes, "
        "welcome_notes = excluded.welcome_notes, admin_notes = excluded.admin_notes, "
        "updated_at = now();"
    )

    lines.append(f"-- Pay entries ({len(entries_sql)} rows; {skipped_entries} skipped, see warnings)")
    # Every batch is its own complete, independently-idempotent statement —
    # the ON CONFLICT clause must repeat per batch, not just on the last
    # one, or re-running this script would 23505 on every row outside the
    # final batch.
    BATCH = 200
    for i in range(0, len(entries_sql), BATCH):
        batch = entries_sql[i : i + BATCH]
        lines.append(pay_entries_insert_header)
        lines.append(",\n".join(batch))
        lines.append(pay_entries_on_conflict)
    lines.append("")

    # ---- custom_requests ----
    cr_header, cr_rows = load_sheet(wb, "CustomPayrollRequests")
    cr_idx = {h: i for i, h in enumerate(cr_header)}
    requests_sql = []
    skipped_requests = 0

    for r in cr_rows:
        email = r[cr_idx["StaffEmail"]]
        pay_period_id = resolve_period_id(r[cr_idx["PayPeriodID"]])
        period = periods_by_id.get(pay_period_id)
        if email not in email_to_name or not period:
            skipped_requests += 1
            warnings.append(
                f"custom_requests: skipped row for {email!r} on {r[cr_idx['EntryDate']]!r} "
                f"(period={pay_period_id!r} unresolved) — re-enter manually if still relevant"
            )
            continue
        start = period["start"]
        if isinstance(start, datetime):
            start = start.date()

        status_raw = (r[cr_idx["Status"]] or "").strip().lower()
        status = status_raw if status_raw in ("approved", "denied", "pending") else "pending"
        approved_amount = r[cr_idx["ApprovedAmount"]]

        # Best-effort link back to the matching pay_entries row (same email,
        # approved amount within 2 cents) — preserves real historical drift
        # (e.g. approved-vs-actually-paid mismatches) rather than "fixing" it.
        pay_entry_id = None
        if approved_amount is not None:
            for legacy_id, (e_email, e_amt) in legacy_id_to_amount.items():
                if e_email == email and abs(e_amt - float(approved_amount)) < 0.02:
                    pay_entry_id = legacy_id
                    break

        requests_sql.append(
            "(" + ", ".join([
                f"(select id from core.users where email = {sql_str(email)})",
                sql_str(email_to_name[email]),
                sql_str(email),
                sql_date(start),
                sql_str(r[cr_idx["Description"]] or ""),
                sql_num(r[cr_idx["AmountRequested"]]) if r[cr_idx["AmountRequested"]] not in (None, "") else "0",
                sql_str(status),
                sql_str(r[cr_idx["AdminNotes"]]),
                sql_num(approved_amount),
                "NULL",
                sql_ts(r[cr_idx["DateApproved"]]),
                sql_str(pay_entry_id),
            ]) + ")"
        )

    lines.append(f"-- Custom payroll requests ({len(requests_sql)} rows; {skipped_requests} skipped)")
    if requests_sql:
        lines.append(
            "insert into payroll.custom_requests (user_id, staff_name, staff_email, pay_period_start, "
            "description, amount_requested, status, admin_notes, approved_amount, decided_by, decided_at, "
            "pay_entry_id) values"
        )
        lines.append(",\n".join(requests_sql) + "")
        lines.append(
            "on conflict (staff_email, pay_period_start, description, amount_requested) do update set "
            "status = excluded.status, admin_notes = excluded.admin_notes, "
            "approved_amount = excluded.approved_amount, decided_at = excluded.decided_at, "
            "pay_entry_id = excluded.pay_entry_id;"
        )
    lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {args.out}")
    print(f"  pay_periods: {len(period_rows_sql)}")
    print(f"  pay_entries: {len(entries_sql)} ({skipped_entries} skipped, {duplicate_entry_ids} duplicate EntryIDs dropped)")
    print(f"  custom_requests: {len(requests_sql)} ({skipped_requests} skipped)")
    print(f"  warnings: {len(warnings)}")
    for w in warnings:
        print(f"  ! {w}", file=sys.stderr)


if __name__ == "__main__":
    main()
